### ISSUE TITLE
Not picking up IRD files

### ISSUE THREAD

**Issue by Tobiwan2077** [13xforever/ps3-disc-dumper#13]
Disc dumper isn't picking IRD's and when I manually look for them they don't show up

**Comment by 13xforever** [comment]
There's zero useful information in this report. Please provide more context. Log file, screenshots of the ird cache folder and settings.

I'm literally dumping new discs all day and everything works fine.

**Comment by Tobiwan2077** [comment]
![1](https://user-images.githubusercontent.com/74786357/99827574-b7be9d00-2b51-11eb-9e7f-d0f32d7ae347.PNG)
It can't find the IRD in the folder I have select
![2](https://user-images.githubusercontent.com/74786357/99827646-d02eb780-2b51-11eb-935b-bd0265ddd2f9.PNG)
Even tho there is one there
![3](https://user-images.githubusercontent.com/74786357/99827667-d7ee5c00-2b51-11eb-836a-aec4a3eb3acc.PNG)
When I go to select it manually it doesn't show up

Just had a look in the log and it says IRD keys are found but on the GUI it say they're isn't any 
[2020-11-20.log](https://github.com/13xforever/ps3-disc-dumper/files/5575001/2020-11-20.log)

**Comment by 13xforever** [comment]
this simply means you have a disc print with different disc key that isn't available, this is not an issue with the disc dumper
