### ISSUE TITLE
Fetch disc keys from Redump.org as alternative decryption method

### ISSUE THREAD

**Issue by SlyCooperReloadCoded** [13xforever/ps3-disc-dumper#16]
I recently got the Japanese Sly Collection added to the Redump database because I was told that this tool automatically grabs disc keys from there, and this disc doesn't have an IRD and wasn't on Redump, so I finally got it added to the database.

Then I tested this tool and it still couldn't find the key.  I then tried dumping a game which did have an IRD but disabling my internet adapters so it couldn't connect to the internet.  My suspicions were confirmed - it doesn't do this, rather it seems to look inside the EXE for keys.

Would it be possible to search Redump.org as a fallback, or have a "Download Latest Keys" button in the tool that redownloads them from Redump.org?

**Comment by 13xforever** [comment]
ps3 disc keys are not public, this is why I asked for permission to distribute snapshot with the dumper, which is being periodically updated

until keys are not public and unavailable without an account, there won't be any autoupdate possible

**Comment by SlyCooperReloadCoded** [comment]
So.... how does it find keys then?  Embedded in the executable?  Can my key be used at all?

**Comment by 13xforever** [comment]
you can always put your disk key in the ird/key cache folder

**Comment by SlyCooperReloadCoded** [comment]
You said it's being updated.  Can I provide my key to be added to the executable since I'm assuming that's how it works?  That's the whole reason why I went through all the trouble of getting it added to Redump.

**Comment by 13xforever** [comment]
redump will publish new snapshot at some point and I'll bundle it at some point, if it isn't already

**Comment by 13xforever** [comment]
Implemented in v3.3.0
