### ISSUE TITLE
Kaspersky is blocking execution of PS3 Disc Dumper as UDS:Trojan.MSIL.Crypt.gen

### ISSUE THREAD

**Issue by JDeraj** [13xforever/ps3-disc-dumper#17]
Kasperksy Anti Virus is preventing PS3 disc dumper from opening.  

Event: Malicious object detected
Component: Application Control
Result description: Detected
Type: Trojan
Name: UDS:Trojan.MSIL.Crypt.gen
Threat level: High
Object path: F:\Downloads\ps3-disc-dumper_win64_3.0.12
Object name: ps3-disc-dumper.exe
Reason: Cloud Protection
MD5: B08B5DC8D256D496C78B2DC7837AF3F9

**Comment by 13xforever** [comment]
I am not Kaspersky and can't do anything about it.

You can submit the file for manual analysis through your account if you have paid subscription or through their public form: https://support.kaspersky.com/us/15328 though free accounts have lowest priority and the analysis can take an undetermined amount of time
