### ISSUE TITLE
[Feature request] Preserve original file modify dates

### ISSUE THREAD

**Issue by NicknineTheEagle** [13xforever/ps3-disc-dumper#19]
Would it be possible to add an option to preserve original modify dates on decrypted game files? It can be useful information in some cases.

**Comment by 13xforever** [comment]
I thought about it, and it should be feasible, but I don't remember what issues prevented me to do it at the time. I'll look at it in January when I'll have some time.

**Comment by 13xforever** [comment]
this is implemented in v3.2, which is in pre-release for now due to linux build, but windows build works fine

**Comment by NicknineTheEagle** [comment]
Thank you.
