### ISSUE TITLE
Test and update linux version if necessary

### ISSUE THREAD

**Issue by 13xforever** [13xforever/ps3-disc-dumper#2]
In theory it should still work, but I haven't tested it since 2.0 branch

**Comment by treymerkley** [comment]
so far it runs as expected, but having the path for the disc hardcoded is kind of limiting. I'm trying to figure out how to pass a path as an argument. I know the format, it would look like `dotnet run -- '/path/to/the disc/or iso'`, but I can't quite make out where to put this in the code.

**Comment by 13xforever** [comment]
You can't use iso, it needs a proper cdrom device associated with it in `/dev`.
Absolutely every modern distro automounts removable media in `/media`, so I really don't see any need for arguments at the moment.

**Comment by treymerkley** [comment]
Oh, really? I believe you, that just seems odd that passing an ISO wouldn't work. I've been doing it manually via ISO for a while now. Plus, all of my stuff mounts to `/dev/sr0` as far as I can tell. 

Wouldn't it be easier just to pass any given path to the system and let it run? I guess I don't understand what `.DetectDisc()` is there for.

**Comment by treymerkley** [comment]
Yeah, so I was thinking maybe have a variable that is, by default, set to `/media`, and then use `args` to pass a string as a different path.

**Comment by 13xforever** [comment]
The issue with iso is that I currently look at [physical devices proc info](../blob/master/Ps3DiscDumper/Dumper.cs#L112) to get the mapping, which is obviously misssing when you mount it through loopback. I guess you can try to read from every physical device manually, but that's kinda meh.

**Comment by treymerkley** [comment]
Oh, okay, so it is a nontrivial change. Thanks for explaining it! Otherwise, the code runs fine on Linux, and can build releases via `msbuild -r`.
