### ISSUE TITLE
Multi-Extent Files

### ISSUE THREAD

**Issue by ghost** [13xforever/ps3-disc-dumper#22]
Does this application properly handle interlaced multi-extent files? These are odd files typically found in 3D discs which use the multi-extent feature of ISO-9660 to interlace each extent with other files. It is what was fixed in [this](https://code.videolan.org/videolan/libudfread/-/commit/f6abda4e725d606e91d15b001edca3f9f095e255) commit to libudfread, and it is the problem that was reported [here](https://www.psx-place.com/threads/jonnysps-ird-library-is-down.35178/page-2#post-315008) for ird files. Would PS3-Disc-Dumper correctly extract the files off an image with such a file structure?

PS3-ISO-Rebuilder doesn't handle this edge case correctly. It assumes all multi-extent files are contiguous and thus calculates MD5 checksums incorrectly while also rebuilding corrupted ISOs in certain cases. I also have a suspicion that team 3K3Y's IRD programs do not handle this edge case correctly.

**Comment by 13xforever** [comment]
I'm relying on OS UDF driver to read file contents (precisely to benefit from error correction and speed up the process).
I'm only reading ISO 9660 table to get the list of all files and their sector mappings (needed to decrypt the bits of files where the filesize does not align with the integer number of sectors, which is most of the time).
To parse the raw filesystem and to build the sector mappings I rely on 3rd party library [DiscUtils](//github.com/DiscUtils/DiscUtils), and as far as I'm aware there's been no issues with dumping discs with interleaved files (I do not have hybrid discs to confirm tho).

**Comment by 13xforever** [comment]
Having tested with a few hybrid PS3 game discs (MGS Legacy Collection and Tekken Hybrid), I can't see any issues with the dumping part. As far as I can see the IRD issues were with rebuilding the ISOs back, which is not relevant to this project.

Closing for now as not affected.
