### ISSUE TITLE
IRD Reminder

### ISSUE THREAD

**Issue by Darkhost1999** [13xforever/ps3-disc-dumper#24]
This is a reminder to update the IRD database https://ps3.aldostools.org/ird.html

Discord bot was updated as seen here https://github.com/RPCS3/discord-bot/commit/b0d11c19796c56d9157b22c9d65c742cffeed505
![image](https://user-images.githubusercontent.com/60384196/181635557-0999354d-994b-4f02-9daf-7fd3a4e536eb.png)

**Comment by 13xforever** [comment]
Implemented in v3.3.0
