### ISSUE TITLE
Inconsistencies in directory timestamps

### ISSUE THREAD

**Issue by NicknineTheEagle** [13xforever/ps3-disc-dumper#25]
It appears that game directories that _only_ have other directories inside them and no files do not get their filestamps set properly (either they're skipped or something resets their timestamp to current time). Directories that have any files inside and empty directories are handled as they should be.

**Comment by 13xforever** [comment]
Can you provide examples of such discs?

**Comment by NicknineTheEagle** [comment]
> Can you provide examples of such discs?

http://redump.org/disc/54429/
http://redump.org/disc/31685/
http://redump.org/disc/28529/
http://redump.org/disc/32426/

**Comment by 13xforever** [comment]
I'll try to look at it next weekend if I'll have some time.

**Comment by NicknineTheEagle** [comment]
It looks like such directories are filtered out over here: https://github.com/13xforever/ps3-disc-dumper/blob/master/IrdLibraryClient/IrdFormat/IsoHeaderParser.cs#L39-L48
This appears to be an optimization that serves to reduce the number of folder creation calls, doesn't look like it's strictly necessary.
