### ISSUE TITLE
助けてください

### ISSUE THREAD

**Issue by kota239** [13xforever/ps3-disc-dumper#27]
アプリケーションのコンポーネントで、ハンドルされていない例外が発生しました。
Value cannot be null. (Parameter 'patch2')

Just-In-Time (JIT) デバッグを呼び出すための詳細については、
ダイアログ ボックスではなく、このメッセージの最後を参照してください。

************** 例外テキスト **************
System.ArgumentNullException: Value cannot be null. (Parameter 'path2')
   at System.IO.Path.Combine(String path1, String path2)
   at UI.WinForms.Msil.MainForm.startDumpingButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 読み込まれたアセンブリ **************
System.Private.CoreLib
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
ps3-disc-dumper
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Windows.Forms
    アセンブリ バージョン:6.0.2.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Windows.Forms.Primitives
    アセンブリ バージョン:6.0.2.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.ComponentModel.Primitives
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.InteropServices
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Drawing.Primitives
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Collections.Specialized
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Drawing.Common
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Threading
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Diagnostics.TraceSource
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Collections
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Configuration.ConfigurationManager
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.ObjectModel
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Microsoft.Win32.Primitives
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.ComponentModel.EventBasedAsync
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Threading.Thread
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Accessibility
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.ComponentModel.TypeConverter
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.ComponentModel
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Numerics.Vectors
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Memory
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Resources.Extensions
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Drawing
    アセンブリ バージョン:6.0.2.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Linq
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Microsoft.Win32.SystemEvents
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Ps3DiscDumper
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Collections.NonGeneric
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
IrdLibraryClient
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Console
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Text.Encoding.Extensions
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Private.Uri
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Diagnostics.Process
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Security.Cryptography.Algorithms
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Security.Cryptography.Primitives
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    アセンブリ バージョン:1.1.4.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Microsoft.WindowsAPICodePack
    アセンブリ バージョン:1.1.4.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.Extensions
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Text.Json
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.Http
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.Primitives
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Diagnostics.Tracing
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Diagnostics.DiagnosticSource
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.Security
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Security.Cryptography.X509Certificates
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Collections.Concurrent
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.Sockets
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Threading.Overlapped
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.NameResolution
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.IO.FileSystem.DriveInfo
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Threading.ThreadPool
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Security.Principal.Windows
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Security.Claims
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Security.Cryptography.Encoding
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Reflection.Emit.Lightweight
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Reflection.Primitives
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Reflection.Emit.ILGeneration
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Text.Encodings.Web
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.Intrinsics
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
EndianBitConverter
    アセンブリ バージョン:1.1.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Xml.ReaderWriter
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Private.Xml
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Text.RegularExpressions
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.WebClient
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.Serialization.Formatters
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Xml.XmlSerializer
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
DiscUtils.Iso9660
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
DiscUtils.Core
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
DiscUtils.Streams
    アセンブリ バージョン:0.16.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.IO.FileSystem
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Linq.Parallel
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.IO.Compression
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Crc32.NET
    アセンブリ バージョン:1.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
netstandard
    アセンブリ バージョン:2.1.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Net.Http.Formatting
    アセンブリ バージョン:5.2.7.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Management
    アセンブリ バージョン:4.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
Microsoft.Win32.Registry
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Runtime.Loader
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Windows.Forms.resources
    アセンブリ バージョン:6.0.2.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Diagnostics.StackTrace
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Reflection.Metadata
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------
System.Collections.Immutable
    アセンブリ バージョン:6.0.0.0
    Win32 バージョン:N/A
    コードベース:
----------------------------------------

************** JIT デバッグ **************

のエラーが出て吸い出せません。

**Comment by 13xforever** [comment]
Please attach log file that should be in the same folder as the dumper exe, by the looks of it you're trying to save decrypted files to a nonexistent location (something like a removable drive that's no longer available)

**Comment by kota239** [comment]
[2022-10-31.log](https://github.com/13xforever/ps3-disc-dumper/files/9896213/2022-10-31.log)
ログファイルを添付します。

**Comment by 13xforever** [comment]
Your settings are broken, and your log is not complete, it's missing the last line from disc detection, so at the very least you had another error before that one. I'll add more logging to the settings and more validation to the settings.

I would not recommend changing anything if you do not understand what they do, simply use defaults.
![image](https://user-images.githubusercontent.com/36445/198930092-4cf88da0-1a21-4b79-bb5f-4d778e665156.png)

**Comment by 13xforever** [comment]
[New test build](https://cdn.discordapp.com/attachments/485204327800242177/1036517438675763282/ps3-disc-dumper_win64_v3.3.2b1.zip) has settings validation, reset button, and additional logging. Plz test and attach new log if it still crashes with the same error (remember to save settings by clicking OK at the end).

**Comment by 13xforever** [comment]
Please reopen if you still have issues with the latest update
