### ISSUE TITLE
Run as admin false-positive on win11 for 3.3.4

### ISSUE THREAD

**Issue by AstroDot** [13xforever/ps3-disc-dumper#30]
Hello,

Last build 3.3.4 is triggering run as Administrative check even when lunched normally.

**Comment by 13xforever** [comment]
Without logs I presume you have uac disabled and it works as expected

**Comment by AstroDot** [comment]
No logs, program not started.

UAC most likely disabled, yes. 

I still have option 'Run as Administrative'. Or you assume that if there is no UAC than everything is done from Administrative?

**Comment by 13xforever** [comment]
I check for elevated context token, with UAC disabled it literally doesn't matter if you select run as administrator or not, if your user is in Administrators user group, it always urns apps with full privileges.

**Comment by AstroDot** [comment]
Still the last change makes last version un-sable in this situation.
Is it possible to change the criticality of this message from exiting application to warning?

**Comment by 13xforever** [comment]
Yes. It is done on purpose. Specifically, to prevent running it as administrator.
Yes, it is possible to still run it, but I'm not helping with it, you'll have to understand the implications, and for that you'll have to understand how the code works, and as a result you'll be able to run it.

**Comment by AstroDot** [comment]
Thanks for explanation!
I have enabled basic level of UAC [following this guide](https://www.minitool.com/news/how-to-disable-uac-in-windows-11.html) and 3.3.4 is working.
Hope it helps someone.
