### ISSUE TITLE
error when dumping

### ISSUE THREAD

**Issue by Annabell-r** [13xforever/ps3-disc-dumper#31]
I get:
   "One or more errors occurred. (Could not find file 'C:\Windows\ird\BLUS31211-472555DCBF41DA9FDFF302D872897D8.ird'.)
i dont know how to fix this

**Comment by 13xforever** [comment]
1. you did not provide log or any relevant information
2. you're running the dumper as an admin
3. you're using an older version that allows to run as an admin
4. it's user error

**Comment by Annabell-r** [comment]
it was user error. the link i followed took me to just the dumper. i didnt realise there was a manual to it
