### ISSUE TITLE
Hang at "Analyzing file structure"

### ISSUE THREAD

**Issue by ikorb** [13xforever/ps3-disc-dumper#33]
Hi,

while trying to dump my copy of "The Witch and the Hundred Knight" (BLES-01987), PS3 Disc Dumper 3.3.5 appears to hang at the "Analyzing file structure" stage. The drive (tested with both BH16NS55 and BU40N) just spins down after some time, so it appears that there is no futher I/O at this point. The app still reacts as expected to the "Cancel" button. The dis appears physically fine and since a plain dump as ISO with another tool finishes without errors, I assume that there are no bad sectors. Other discs can be dumped on the same drives+system without any issues.

Log file:
[hundredknight.log](https://github.com/13xforever/ps3-disc-dumper/files/11585035/hundredknight.log)

**Comment by 13xforever** [comment]
I have this disc and it works just fine, and even if there are no errors in the log, it's probably an issue with drive or the disc. Try restarting the PC and make sure the disc is not scratched.

**Comment by ikorb** [comment]
Unfortunately trying it on another (freshly booted) system doesn't change the behaviour. There are also no messages in the Windows event log that would suggest disc read errors.

**Comment by ikorb** [comment]
Ok, found the root cause: Not enough patience. =)

The disc dumps fine, it just takes about 20-30 minutes in the "Analyzing file structure" phase, possibly due to the large number (~10k) of small files. A progress indicator (or improved algorithmic complexity) for this phase might be nice in future versions.

**Comment by 13xforever** [comment]
It's not the number of files, I'm already caching the whole toc sectors in memory before parsing the filesystem, it's something with the drive or the disc; I have samples with 30k+ files and it usually takes a couple of seconds to analyze the structure
