### ISSUE TITLE
"Please do not run software as Administrator..." preventing from program execution unnecessarily

### ISSUE THREAD

**Issue by egdose** [13xforever/ps3-disc-dumper#34]
I'm working on a Windows 10 machine with only one user profile (Administrator). I have UAC disabled on my system (personal preference). I'm not sure if it means that it'll always run programs as administrator, but as far as I know, the program requests for rights it needs, and UAC appears once those rights get to admin territory.

Coming to the issue, I can't seem to be able to execute the dumper program because I always get that error. I think there needs to be an option where I should be able to acknowledge that I know I'm running this program as administrator, and I will bare the consequences if there are any. I hope it makes sense. 

I'll try to create a pull request to fix this issue. Let me know if there is anything more to discuss; I'm happy to discuss in the comments here.

**Comment by 13xforever** [comment]
UAC prevents users with admin privileges to run code with said privileges _unless_ program requests elevation, at which point it presents the elevation dialog to the user. If you have UAC disabled, you run _everything_ with admin perms and there's no way to drop them through normal means.

The check as implemented is _designed_ to prevent this software in the manner you're describing. You're violating all good security practices and recommendations by using the built-in Administrator account and by disabling UAC completely.

There _will not_ be an option to disable this behavior through easily accessible means. If you want to shoot yourself in the foot, there's already a way, but you'll have to work it out yourself and use it at your own descretion.

**Comment by 13xforever** [comment]
Unless you can provide logs and reproducible setup where this is behaves in the way it was not designed, this issue is invalid.

**Comment by egdose** [comment]
I'll try this again after enabling UAC. Thanks for the response.

**Comment by egdose** [comment]
Yeah that checks out, enabling UAC allows it to run the program. I didn't know that before.

Thanks anyway!

**Comment by ElektroStudios** [comment]
Workaround to bypass restrictions (it works on an Administrator / built-in Administrator account with UAC disabled):

1. Download [PSExec from SysInternals](https://learn.microsoft.com/en-us/sysinternals/downloads/psexec).
2. Run PSExec with this command:
   - `PSExec.exe -l "ps3-disc-dumper.exe"`

**Comment by ElektroStudios** [comment]
> UAC [prevents](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/user-account-control/how-it-works) users with admin privileges to run code with said privileges _unless_ program requests elevation, at which point it presents the elevation dialog to the user. If you have UAC disabled, you run _everything_ with admin perms and there's no way to drop them through normal means.
> 
> The check as implemented is _designed_ to prevent this software to be used in the manner you're describing. You're violating all good security practices and recommendations by using the built-in Administrator account and by disabling UAC completely.
> 
> There _will not_ be an option to disable this behavior through easily accessible means. If you want to shoot yourself in the foot, there's already a way, but you'll have to work it out yourself and use it at your own discretion.

The only thing you achieve this way is generate rejection and animosity.

You should not use your program to try to "educate" users or interfere with their lives and preferences. Everything you have said in that comment is a very subjective opinion, and debatable.

You should limit yourself to offering functionality through software, and then if you want you can start UAC awareness campaigns, but not through your software in a forced, intrusive, and pedantic way with those types of comments.

Believe me, I don't "shoot myself in the foot," but you do.

Without acrimony.

**Comment by 13xforever** [comment]
That's the third time you say "bye", but you keep spamming your own opinions, so I'll help you a bit.
