### ISSUE TITLE
Windows 7 not supported?

### ISSUE THREAD

**Issue by xVenti** [13xforever/ps3-disc-dumper#35]
Versions 3.3.4, 3.3.5 and 3.3.6 seem to not properly run on Windows 7.
When trying to run the program, it shows an error message, saying not to run the program as an administrator.

![img](https://github.com/13xforever/ps3-disc-dumper/assets/64586733/2ef2208e-e864-40eb-8f2a-fcf65df702e7)

Version 3.3.3 runs as expected.

**Comment by 13xforever** [comment]
And no, no one supports obsolete OS.
