### ISSUE TITLE
Ps3 Disc Dumper Won't go further after "looking for disc key"

### ISSUE THREAD

**Issue by MehdiImmortal** [13xforever/ps3-disc-dumper#36]
I mounted my iso on my drive and it was detected by the app, however, the app somehow freezes and won't go any further after detecting the iso.

**Comment by 13xforever** [comment]
1. Why are you doing this? I'm only officially supporting dumping of physical discs.
2. You didn't even provide any additional info, such as dumper log, disc information, and how the iso was made.

**Comment by MehdiImmortal** [comment]
> * Why are you doing this? I'm only officially supporting dumping of physical discs.
> * You didn't even provide any additional info, such as dumper log, disc information, and how the iso was made.

1- Because I couldn’t find any physical copies of the games I was looking for in my local stores anymore.
2- I downloaded the redump isos from sites that I can’t mention here but they are easy to find in google 
3- The games I tried to decrypt : Lollipop chainsaw, Folklore for now 
4- how can I provide you the information that you need ( I’m a begginer in this matter sorry )

**Comment by 13xforever** [comment]
Piracy is not condoned and not supported here. All mentioned games were dumped previously just fine using original discs and supported drives.

Unless you have issues with physical disc in good condition, you will not get any help here or at any official support channel.

Please buy the games, you’re required to dump your own copy.

**Comment by MehdiImmortal** [comment]
Ok I’ll figure it out somehow myself, thanks

**Comment by jkrehm** [comment]
Since many of the issues are redirected here as duplicates I'll say that I was getting this while trying to dump one of my discs and it was because I had MakeMKV open in the background. That seems to have prevented PS3 Disc Dumper from having direct access to my drive. Once I closed MakeMKV I was able to dump my disc.
