### ISSUE TITLE
Program loops trying to access Blu-Ray Drive

### ISSUE THREAD

**Issue by KingZach79** [13xforever/ps3-disc-dumper#37]
I'm using a computer running Windows 11 along with a required Blu-Ray drive. When I insert any game, the software seems to loop over and over. It will detect a PS3 game disc, look for a disc key and start over until I close the program. When I check the log, it seems the software is denied access to both drives I have installed on my setup. When I ran an earlier version, I had the same issue but when I could run it as an admin, I was able to access the drives and dump the game. I have no problems with either version when I install the Blu-Ray back on my older Windows 10 machine. Attached is the log file. Thoughts?

[2023-07-20.log](https://github.com/13xforever/ps3-disc-dumper/files/12114791/2023-07-20.log)

**Comment by 13xforever** [comment]
It means some other software has opened the raw devices and keeping them open. I can reproduce this if I run two dumpers for example, only the first instance will have the access until it’s closed or finished with the disc.

The difference between win10 and win11 is coincidental, you simply have different software installed between them.

You can probably use SysInternals Process Explorer or similar tool to see who is keeping \\.\CDROM0 open.

**Comment by KingZach79** [comment]
Not sure why I didn't see the screenshot in the Email, but that is extremely helpful. I couldn't figure out how to check it using the software you mentioned. I will run that Handle / DLL Substring check tomorrow evening and let you know. Thank you so much!

What I also noticed while swapping drives between computers is that both drives are connected to a [SATA Expansion Card](https://www.amazon.com/10Gtek-Profile-Bracket-Controller-Expansion/dp/B09Y1PMZ2W?th=1) I have installed on my media server. I'm thinking something on that is causing problems. After I test what you suggested, I'm going to disconnect the Blu-Ray Drive from the card and plug directly into the motherboard. Wish me luck!

**Comment by KingZach79** [comment]
So, I can't use this utility while PS3 Disc Dumper is open. When I search "\Device\CdRom1", it sits trying to search while PS3 Disc Dumper goes through the infinite loop. If I leave the PS3 game disc in the Blu-Ray and perform the search, I get the following:

![Screenshot 2023-07-26 214008](https://github.com/13xforever/ps3-disc-dumper/assets/140124377/9fb3fea2-ba6e-4684-9fa0-10e02fcc1e38)

Since I have the same results twice for "explorer.exe", does this mean something is keeping the raw device opened or is that normal? (I assume it is) I'm going to try tomorrow to unplug from the SATA Expansion Card and plug directly into the motherboard. I need to make sure no one is on the media server while it's down. I'll keep you posted.

**Comment by KingZach79** [comment]
Good News! After unplugging the Blu-Ray Drive from the SATA Expansion Card and plugging it directly into the motherboard, it's working properly. This might resolve some other issues I've been having. I'm going to have to rearrange some of the hardware in the case to make things work they way I want to, but there you have it. Anything else you want me to try before I close this out? Otherwise, thanks for pointing me in the right direction.

**Comment by 13xforever** [comment]
fwiw I can reproduce this issue when running in a vm, but that's related to remote access group policy that disables direct access to all removable media by default.

There are related group policies to explicitly disable access completely for classes of devices, but I doubt it's related to this issue.

**Comment by KingZach79** [comment]
Holy cow - It's totally related to the issue! I access my media server via RDP (Remote Desktop Protocol) on my desktop computer. I have a unique setup in my apartment. I did not realize that their was a Group Policy that disabled "direct access to all removable media by default". I've made the changes and will try it out once I can restart the server. I have one friend that's using it right now. You are awesome!!!

**Comment by 13xforever** [comment]
Run `gpedit.msc`, the policy is at `Computer Configuration > Administrative Templates > System > Removable Storage Access > All removable storage: Allow direct access in remote sessions`

**Comment by KingZach79** [comment]
I finally got a chance to restart the server. Everything works!!! Thank you so much for helping me troubleshoot this, you are a true gent. Have a great day!

**Comment by RachelWofle** [comment]
> Run `gpedit.msc`, the policy is at `Computer Configuration > Administrative Templates > System > Removable Storage Access > All removable storage: Allow direct access in remote sessions`

Well I'll be damned, this was my issue too.
Hey, seeing as this is entirely fixable on the user's end, would you consider adding a helper message to avoid this coming up again? Something like "Direct access refused: are you connected remotely?" with a link to this thread or even just a mention of this policy item would do.

**Comment by 13xforever** [comment]
It's on the list with very low priority.

**Comment by 13xforever** [comment]
It is now implemented in v4.0.9

**Comment by RachelWofle** [comment]
Works great! Appreciate it.
