### ISSUE TITLE
PS3 disc dumper wont decrypt because access denied

### ISSUE THREAD

**Issue by olloof** [13xforever/ps3-disc-dumper#40]
whenever i try to decrypt and copy the file it says ine or more errrors occured. (access to the path [game] is denied.) How can i fix this and stop it from happpening?

**Comment by 13xforever** [comment]
I can't help if you do not provide any details. Start with uploading the log. What does the error say _exactly_? Does this happen with every disc or some specific one? Did it work before? What operating system do you use? Do you actually have permission to write wherever you're trying to dump the disc?
