### ISSUE TITLE
"No valid disc decryption key was found"

### ISSUE THREAD

**Issue by ROK66688** [13xforever/ps3-disc-dumper#41]
Please help me.
Like you can see in the log, there is an endless loop.
I tried several games, everytime the same.

[2023-08-06.log](https://github.com/13xforever/ps3-disc-dumper/files/12270308/2023-08-06.log)

**Comment by 13xforever** [comment]
If there's no matching key, then there's no matching key; use your ps3 to dump the discs
there will be a new update in a few weeks with more debug information being logged, you can try to wait (but I'm 100% positive the issue is not the dumper)

**Comment by 13xforever** [comment]
The new version preview is up, you can try it at https://github.com/13xforever/ps3-disc-dumper/releases/tag/v4.0.0-beta1
