### ISSUE TITLE
Folder size too small?

### ISSUE THREAD

**Issue by 760194962** [13xforever/ps3-disc-dumper#43]
So today i was dumping Short Peace - Tsukigime Ranko no Ichiban Nagai Hi (Japan)
But i only get 4gb folder while the iso is 20gb.

I know the disc is containg bluray movie files of the anime Short Peace so i guess it just didnt dump the video files?
However i ended up being unable to run the dumped iso with my PS3 console

Maybe it's because it is hybird?

**Comment by 760194962** [comment]
I tried again and it's ok now. The folder size is 20gb. Sorry for disturbing

**Comment by 13xforever** [comment]
Dumper will copy all the files, however blu-ray video/audio is protected using AACS/BD+ and not PS3 game encryption, so the copied hybrid parts will still be encrypted, you need to dump those separately using normal video/audio ripping tools

**Comment by 13xforever** [comment]
no, video encryption keys are stored in a special service zone and are only accessible for certified blu-ray firmware, you can't read that data through normal means, but that's not related to ps3 games
