### ISSUE TITLE
Dumping Tekken Hybrid failed

### ISSUE THREAD

**Issue by CaptainHIT** [13xforever/ps3-disc-dumper#45]
Tekken Hybrid (Europe) (En,Ja,Fr,De,Es,It,Ko).iso
MD5 c33be6225a08a1bbf2291ee396164b2e

PS3 Disc Dumper fails to dump the disc
Error message:
An item with the same key has already been added. Key: 90430

Product Code: BCES01454
Dump Size: 66,93 GB (238 files)
Disk Key: A1DC5F97_CC8A9509_47F8FC27_30A3FE44.ird

The destination dir is empty, the ird folder has no other ird files.
![Screenshot 2023-09-25 210849](https://github.com/13xforever/ps3-disc-dumper/assets/16159412/a25d3033-d287-4699-a97c-81a82b19df10)

ISO mounted with DAEMON Tools Lite 10.13.0.1456

**Comment by 13xforever** [comment]
No log file attached, also no support for isos and pirated content.

**Comment by 13xforever** [comment]
Well I guess you can always reopen if you manage to reproduce on real disc with real drive
