### ISSUE TITLE
Asassin's Creed [BLJM60110] was read wrong ProductCode [BLJM 60050]?

### ISSUE THREAD

**Issue by nassau-tk** [13xforever/ps3-disc-dumper#46]
I reported this issue on RPCS3.
https://github.com/RPCS3/rpcs3/issues/14687

But, I find the strange point on PS3 Disk Dumper.
See,Below...
THE Package & Disk printed [BLJM 60110] but Dumper says [BLJM60050].
And Redump.org has no [BLJM 60050].
Is it dump correctly?

![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/efdf5114-0306-4682-a4d8-26afa80ad617)

![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/2b9bb620-024d-40ea-a361-cfd9eaf0d358)

![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/d0ad5bc6-83c9-468f-9286-d69942916421)

![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/f8733acf-8b47-42d3-ad03-0f4698590813)

![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/c11c5d1a-3a59-4ca3-9020-853390d9533d)

**Comment by 13xforever** [comment]
Disc dumper is reading the disc metadata directly from disc, so this is what's been written to it. 

The product code on packaging being different is common, different game editions often package the same disc inside.

I never heard of the code being different on the disc label itself though, but I've seen enough mastering errors to know Sony had often fucked up in various ways, so wouldn't be surprised it's a misprint.

**Comment by 13xforever** [comment]
Wrong product code will not affect the decryption, but can affect validation status. Also please attach dumper log for this disc.

**Comment by nassau-tk** [comment]
Thank you for your reply!
The log is here.
[2023-09-28.log](https://github.com/13xforever/ps3-disc-dumper/files/12774499/2023-09-28.log)

**Comment by 13xforever** [comment]
Yeah, both disc and game metadata have product code BLJM60050, so it's just the packaging/disc print that's different. There is no disc read errors, so your dump should be fine.

I've added more information in logs in v4.0.4 that should be up soon. If you can upload a new log from it do double check, that would be great. Just put the disc and wait until it finds the key, no need to actually dump the files.

**Comment by nassau-tk** [comment]
OK！
Thank you!!
I'll try it!!

**Comment by nassau-tk** [comment]
Hi!
I tried again but it's not work.
And,I tried talking on Discord about it.
Please se  below...
![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/12dea0f0-63e3-4a3d-9719-96a7af081011)

![image](https://github.com/13xforever/ps3-disc-dumper/assets/48179091/0aa2ef99-7d92-4b7d-bdf3-e7e5c8a6d2c1)

How do you think about it?

**Comment by Darkhost1999** [comment]
I thought what would happen was they'd update their disc dumper and upload a new dumper log as requested to re-validate this. Although I have seen the IDs not match up with an example game like Skyrim before. Disc reporting not legendary edition gamedata at least. I don't think the issue is with dumping the game.
