### ISSUE TITLE
[Feature Request] Add support for another IRD site

### ISSUE THREAD

**Issue by FlexBy420** [13xforever/ps3-disc-dumper#52]
https://jajwan.free.nf/ has IRDs from both Aldos and Zar's sites but also contains more IRDs that both don't have. Like for example korean release of Mirror's Edge BLKS20094

It also has a github repo containing the IRD files
https://github.com/FlexBy420/playstation_3_ird_database

**Comment by 13xforever** [comment]
It's super slow (50-60s on average to load), and there's no api/server-side filter that I could see, so it won't be a very good source. I'll keep it in mind as a backup, but right now it's not very useable.

Even generating a static page and hosting it on gh pages will probably work better than dynamically generating the list via php as it is now.

**Comment by 13xforever** [comment]
haha I've managed to cobble some [static website generator](https://github.com/13xforever/ird-db/tree/gh_pages_workflow) that automatically updates github pages on every commit that contains ird files, just needs some scripts for UI and documentation. I'll make a pr later, and then I can add that to the dumper.

https://13xforever.github.io/ird-db/all.json
