### ISSUE TITLE
Removal of CLI project

### ISSUE THREAD

**Issue by romatthe** [13xforever/ps3-disc-dumper#55]
Hi, thanks for maintaining this great project!

I noticed that with the release of v4.1.0 you've remove the `UI.Console` project together with the legacy WinForms frontend. Is there a particular reason for this? I'm used to using the CLI on Linux, and it was actually pretty handy because I scripted it (with `--interactive=false`) to dump a disc, compress the result, give the archive a proper name, and `scp` it over to my storage machine, clean up the results etc, etc. This is especially handy for starting up a job when I'm away from my PC for a while. Without the CLI I have to do all of those steps manually.

The Avalonia UI sounds very nice, but I think it's extremely handy to still have the CLI on occasion. Is there any way this can be restored?

Thanks!

**Comment by 13xforever** [comment]
Legacy projects didn't get any attention for years (and I haven't published console build even longer), and you can still manually merge main into the legacy branch if you need to build it yourself.

The version you already have will update the keys and the chances of core logic changes is very low, so I don't see why you can't keep using the version you already have.
