### ISSUE TITLE
This software will not work on a built-in Administrator account.

### ISSUE THREAD

**Issue by ElektroStudios** [13xforever/ps3-disc-dumper#58]
I'm very disappointed that this software will not work / open on a [built-in Administrator account](https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/enable-and-disable-the-built-in-administrator-account). Instead, a _"Unsupported security context"_ error message will be shown, and the program will close itself.

So I have two options from this point:

1. To waste time into creating and configuring a new, limited user account and with UAC enabled just to be able use this program.
2. Ignore this program that is causing me a problem, and write a complaint on his GitHub repository.

I chose the second option, because a software should not intrude on the end user's habits or preferences just to tell him to use a kind of user account with specific (lower) privileges or having UAC disabled. This software is too invasive and impertinent in that regard. I think a software has to adapt to the end user's environment, not the other way around.

I'm not expecting an answer or solution, I just wanted to try this software... not to use it right now, but to keep it as a tool available in my personal PS3 toolbox folder, but I couldn't use it due the restrictions, and this has been my personal opinion.

**Comment by 13xforever** [comment]
k?
