### ISSUE TITLE
i dont know what im doing

### ISSUE THREAD

**Issue by Flaming-Phaser** [13xforever/ps3-disc-dumper#59]
how do i even start the dump? im looking for a file with .exe at the end, if that isnt the executable.....then i have no clue which of these files actually starts the dump

**Comment by Flaming-Phaser** [comment]
like, i downloaded it, im looking through it, how do i start a dump? every single file is a text, code thing, but there is no exe file

I re downloaded it

so im assuming im supposed to do something, and there isnt actually an exe file in here

**Comment by 13xforever** [comment]
If you can't download correct zip from the [Releases](https://github.com/13xforever/ps3-disc-dumper/releases/latest), then idk how to help

**Comment by Flaming-Phaser** [comment]
I must have been on crack when i did this shit last year, or maybe I have brain fog. Cuz none of these steps are looking familiar
