### ISSUE TITLE
Crashes when trying to go to settings

### ISSUE THREAD

**Issue by Aasikki** [13xforever/ps3-disc-dumper#62]
Every time I try to click the settings icon, the program hangs for few seconds and crashes. Dumping works fine still.
Windows 11 23H2, tried reinstalling dotnet but didn't help.
[2024-02-29.log](https://github.com/13xforever/ps3-disc-dumper/files/14451415/2024-02-29.log)

**Comment by 13xforever** [comment]
The log is empty, so I need some details: what OS? are there any entries with stack trace in system journal after crash (<kbd>win</kbd>+<kbd>x</kbd> > Event Viewer > Windows Logs > Application)? is the disc already inserted? have you tried waiting for the scan to end?

There's nothing special in the settings that could cause a crash unless it's something system-wide that breaks the UI rendering.

**Comment by 13xforever** [comment]
well that's not encouraging, it's all pure avalonia stack, and without the way to reproduce the issue, I can only hope it'll go away with future library updates

**Comment by 13xforever** [comment]
Please try the latest update and report if it fixes the crash or if we need to wait 11.1

**Comment by Aasikki** [comment]
> Please try [the latest update](https://github.com/13xforever/ps3-disc-dumper/releases/latest) and report if it fixes the crash or if we need to wait 11.1

The new update works perfectly for me! Fixed.
