### ISSUE TITLE
"Unsupported security context" error

### ISSUE THREAD

**Issue by Triramama** [13xforever/ps3-disc-dumper#65]
I'm getting this error when trying to start the app, any fix?
![image](https://github.com/13xforever/ps3-disc-dumper/assets/97356540/ab6d7a67-f27c-494e-ba4e-698615ad7cb4)

**Comment by 13xforever** [comment]
It literally has a help link. The solution is to not run everything as administrator.

**Comment by 13xforever** [comment]
duplicate of #34
