### ISSUE TITLE
Handling of bulk ISOs?

### ISSUE THREAD

**Issue by dcuellar** [13xforever/ps3-disc-dumper#69]
Hello. Great tool. I just wanted to know if there was a way to handle more than 1 at a time or a script that could be used to mount, run ps3 disc dumper, unmount and then repeat for a group of PS3 ISO files in a specified folder?

Additionally, I was wondering why icons in the name like TM aren't being copied over to the game title on the folder? It just leaves a blank space. Is there a setting I need to adjust on windows to allow it?

**Comment by 13xforever** [comment]
Some symbols are stripped for compatibility reasons, there is no setting to change it. If you really want it, you'll have to rename the folder manually.

Dumping ISOs is not supported and will never be supported, as per #49.

**Comment by dcuellar** [comment]
Gotcha. Thanks for the quick response.
