### ISSUE TITLE
Add the ability to run the application as a docker container

### ISSUE THREAD

**Issue by Mosaad-20** [13xforever/ps3-disc-dumper#70]
It would be nice if the application be hosted in home labs and have the dumper there.

**Comment by 13xforever** [comment]
I don't see how that would be useful or even practical, not to mention the complete waste of bandwidth and time spent on implementing this.

You'll have to do it yourself, I'm not touching docker with a ten-foot pole.

**Comment by Mosaad-20** [comment]
My case is kinda specific, I have a dumping pc for any thing I want to create backup for and it's a hassle to switch monitors every time I want to dump a disc. If there is an exposable api or a cli command such that if a disc inserted you can hit the api or just run a docker exec through ssh to trigger scan and download the dumped file.
