### ISSUE TITLE
App will crash when both run and saving to network drive

### ISSUE THREAD

**Issue by richpanda1214** [13xforever/ps3-disc-dumper#71]
Unable to start the dumping when the app is opened from my NAS and when trying to save to my NAS. I had to copy the .exe to my desktop and save to my NAS later.

**Comment by 13xforever** [comment]
This is inactionable. What are the details? What's the stack trace either from the message box or from the Windows event journal. How the drive is mounted (filesystem, protocol, is it mounted as a drive or a network path, etc), etc.
