### ISSUE TITLE
Tried To Dump an ISO file but it said the disc was invalid and i had 183 invalid files. 

### ISSUE THREAD

**Issue by GrimJack95** [13xforever/ps3-disc-dumper#73]
I downloaded MGS4 from the reddit ROM list. Found a link on mycrient for it. It didn't come with a decryption key so i thought i might be able to use ps3 disk dumper but i've hit another road block. not sure where to go from here to get this ISO file decrypted and working.
[2024-08-25.log](https://github.com/user-attachments/files/16743232/2024-08-25.log)

this is  the log it gave me. I don't really know what I'm looking at here so I'm hoping someone who does know can help me out.

**Comment by 13xforever** [comment]
Piracy is not supported and not tolerated here. Only real disc in real drive.
