### ISSUE TITLE
Issue with dumping MGS4

### ISSUE THREAD

**Issue by CrimsonCraftyCat** [13xforever/ps3-disc-dumper#74]
[2024-09-05.log](https://github.com/user-attachments/files/16884287/2024-09-05.log)

From the log I uploaded, there's a data error when using the disc dumper tool when dumping MGS4 that says, 
2024-09-05 02:32:50	3957693	ERROR	Data error (cyclic redundancy check). : 'E:\PS3_GAME\USRDIR\o\MGO2.SELF'
System.IO.IOException: Data error (cyclic redundancy check). : 'E:\PS3_GAME\USRDIR\o\MGO2.SELF'

Whilst this is happening, there's no progress in the dumper tool, the progress bar stops. Not sure what's happening and how to resolve it, I attempted using administrator privileges to see if it would change anything and I was met with a prompt to not open the program with admin privileges. If I could get some assistance, that would be awesome!

**Comment by 13xforever** [comment]
It's a disc read error. Your disc is damaged, and your drive can't read the data. You can try cleaning the surface, and dump multiple times, but you'll probably need a new copy.
